# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - johnfalcocloudresume

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_64200ab70dc04404baabdbcaebaf7161 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_07e572f9ea504368ae5d5e11f784b0d3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_64200ab70dc04404baabdbcaebaf7161 }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'johnfalcocloudresume'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ee053ff797bb4904a29da243e0a60056 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_64200ab70dc04404baabdbcaebaf7161 }}/appsvc/wordpress-alpine-php:${{ github.sha }}'